### ISSUE TITLE
Allow users to mute instances instead of completely blocking them

### ISSUE THREAD

**Issue by pinkgator** [Taullo/Ruffy#31]
### Pitch

I would like the ability to mute other instances on the user end instead of completely blocking them, so that people on that instance can still see and interact with their posts but they don't have to see the posts from that instance.

Alternatively, you could allow users to apply an "instance name" flag to filter keywords, which would allow people to have more control over what contexts the posts are muted in and allow them to collapse posts instead of hiding them entirely.

### Motivation

Some instances are focused almost entirely on niche kinks such as vore, transformation, inflation, etc., and a lot of them don't require it to be properly tagged. Instead of being forced to limit them at the instance level to prevent users from being unable to filter posts or forcing individual users to completely block huge communities of people from which they might get business from, it would be great for folks to have the option to just hide posts from it on their timeline.

**Comment by Taullo** [comment]
Added with 1bc90dc
