### ISSUE TITLE
Tags not added properly when editing

### ISSUE THREAD

**Issue by gaylie** [Taullo/Ruffy#38]
### Steps to reproduce the problem

1. Make a post and add tags via the new "Add #hashtags to your post" bar.
2. You can see the tags appearing at the bottom of the post, rather than in the description.
3. Edit the post. The tags will now appear in the description, rather than the "Add #hashtags to your post" bar.
4. Save the edit, and the tags will now appear in the description as well, rather than at the bottom of the post.

### Expected behaviour

The tags should've been in the "Add #hashtags to your post" bar upon editing, and then displayed at the bottom of the post.

### Actual behaviour

The tags appear in the description after editing.

### Mastodon instance

https://aethy.com/

### Mastodon version

4.3.0-alpha.1

### Browser name and version

LibreWolf 124.0.1-1

### Operating system

Windows 11

**Comment by Taullo** [comment]
Fixed with df61191
